framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            orchestrator:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: orchestrator
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            llm:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: llm
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            tool:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: tool
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            App\Research\Message\Orchestrator\*: orchestrator
            App\Research\Message\Llm\*: llm
            App\Research\Message\Tool\*: tool
